(function($){'use strict';if(typeof wpcf7==='undefined'||wpcf7===null){return;}
wpcf7=$.extend({cached:0,inputs:[]},wpcf7);$(function(){wpcf7.supportHtml5=(function(){var features={};var input=document.createElement('input');features.placeholder='placeholder'in input;var inputTypes=['email','url','tel','number','range','date'];$.each(inputTypes,function(index,value){input.setAttribute('type',value);features[value]=input.type!=='text';});return features;})();$('div.wpcf7 > form').each(function(){var $form=$(this);wpcf7.initForm($form);if(wpcf7.cached){wpcf7.refill($form);}});});wpcf7.getId=function(form){return parseInt($('input[name="_wpcf7"]',form).val(),10);};wpcf7.initForm=function(form){var $form=$(form);$form.submit(function(event){if(typeof window.FormData!=='function'){return;}
wpcf7.submit($form);event.preventDefault();});$('.wpcf7-submit',$form).after('<span class="ajax-loader"></span>');wpcf7.toggleSubmit($form);$form.on('click','.wpcf7-acceptance',function(){wpcf7.toggleSubmit($form);});$('.wpcf7-exclusive-checkbox',$form).on('click','input:checkbox',function(){var name=$(this).attr('name');$form.find('input:checkbox[name="'+name+'"]').not(this).prop('checked',false);});$('.wpcf7-list-item.has-free-text',$form).each(function(){var $freetext=$(':input.wpcf7-free-text',this);var $wrap=$(this).closest('.wpcf7-form-control');if($(':checkbox, :radio',this).is(':checked')){$freetext.prop('disabled',false);}else{$freetext.prop('disabled',true);}
$wrap.on('change',':checkbox, :radio',function(){var $cb=$('.has-free-text',$wrap).find(':checkbox, :radio');if($cb.is(':checked')){$freetext.prop('disabled',false).focus();}else{$freetext.prop('disabled',true);}});});if(!wpcf7.supportHtml5.placeholder){$('[placeholder]',$form).each(function(){$(this).val($(this).attr('placeholder'));$(this).addClass('placeheld');$(this).focus(function(){if($(this).hasClass('placeheld')){$(this).val('').removeClass('placeheld');}});$(this).blur(function(){if(''===$(this).val()){$(this).val($(this).attr('placeholder'));$(this).addClass('placeheld');}});});}
if(wpcf7.jqueryUi&&!wpcf7.supportHtml5.date){$form.find('input.wpcf7-date[type="date"]').each(function(){$(this).datepicker({dateFormat:'yy-mm-dd',minDate:new Date($(this).attr('min')),maxDate:new Date($(this).attr('max'))});});}
if(wpcf7.jqueryUi&&!wpcf7.supportHtml5.number){$form.find('input.wpcf7-number[type="number"]').each(function(){$(this).spinner({min:$(this).attr('min'),max:$(this).attr('max'),step:$(this).attr('step')});});}
$('.wpcf7-character-count',$form).each(function(){var $count=$(this);var name=$count.attr('data-target-name');var down=$count.hasClass('down');var starting=parseInt($count.attr('data-starting-value'),10);var maximum=parseInt($count.attr('data-maximum-value'),10);var minimum=parseInt($count.attr('data-minimum-value'),10);var updateCount=function(target){var $target=$(target);var length=$target.val().length;var count=down?starting-length:length;$count.attr('data-current-value',count);$count.text(count);if(maximum&&maximum<length){$count.addClass('too-long');}else{$count.removeClass('too-long');}
if(minimum&&length<minimum){$count.addClass('too-short');}else{$count.removeClass('too-short');}};$(':input[name="'+name+'"]',$form).each(function(){updateCount(this);$(this).keyup(function(){updateCount(this);});});});$form.on('change','.wpcf7-validates-as-url',function(){var val=$.trim($(this).val());if(val&&!val.match(/^[a-z][a-z0-9.+-]*:/i)&&-1!==val.indexOf('.')){val=val.replace(/^\/+/,'');val='http://'+val;}
$(this).val(val);});};wpcf7.submit=function(form){if(typeof window.FormData!=='function'){return;}
var $form=$(form);$('.ajax-loader',$form).addClass('is-active');$('[placeholder].placeheld',$form).each(function(i,n){$(n).val('');});wpcf7.clearResponse($form);var formData=new FormData($form.get(0));var detail={id:$form.closest('div.wpcf7').attr('id'),status:'init',inputs:[],formData:formData};$.each($form.serializeArray(),function(i,field){if('_wpcf7'==field.name){detail.contactFormId=field.value;}else if('_wpcf7_version'==field.name){detail.pluginVersion=field.value;}else if('_wpcf7_locale'==field.name){detail.contactFormLocale=field.value;}else if('_wpcf7_unit_tag'==field.name){detail.unitTag=field.value;}else if('_wpcf7_container_post'==field.name){detail.containerPostId=field.value;}else if(field.name.match(/^_wpcf7_\w+_free_text_/)){var owner=field.name.replace(/^_wpcf7_\w+_free_text_/,'');detail.inputs.push({name:owner+'-free-text',value:field.value});}else if(field.name.match(/^_/)){}else{detail.inputs.push(field);}});wpcf7.triggerEvent($form.closest('div.wpcf7'),'beforesubmit',detail);var ajaxSuccess=function(data,status,xhr,$form){detail.id=$(data.into).attr('id');detail.status=data.status;var $message=$('.wpcf7-response-output',$form);switch(data.status){case'validation_failed':$.each(data.invalidFields,function(i,n){$(n.into,$form).each(function(){wpcf7.notValidTip(this,n.message);$('.wpcf7-form-control',this).addClass('wpcf7-not-valid');$('[aria-invalid]',this).attr('aria-invalid','true');});});$message.addClass('wpcf7-validation-errors');$form.addClass('invalid');wpcf7.triggerEvent(data.into,'invalid',detail);break;case'spam':$message.addClass('wpcf7-spam-blocked');$form.addClass('spam');$('[name="g-recaptcha-response"]',$form).each(function(){if(''===$(this).val()){var $recaptcha=$(this).closest('.wpcf7-form-control-wrap');wpcf7.notValidTip($recaptcha,wpcf7.recaptcha.messages.empty);}});wpcf7.triggerEvent(data.into,'spam',detail);break;case'mail_sent':$message.addClass('wpcf7-mail-sent-ok');$form.addClass('sent');if(data.onSentOk){$.each(data.onSentOk,function(i,n){eval(n)});}
wpcf7.triggerEvent(data.into,'mailsent',detail);break;case'mail_failed':case'acceptance_missing':default:$message.addClass('wpcf7-mail-sent-ng');$form.addClass('failed');wpcf7.triggerEvent(data.into,'mailfailed',detail);}
wpcf7.refill($form,data);if(data.onSubmit){$.each(data.onSubmit,function(i,n){eval(n)});}
wpcf7.triggerEvent(data.into,'submit',detail);if('mail_sent'==data.status){$form.each(function(){this.reset();});}
$form.find('[placeholder].placeheld').each(function(i,n){$(n).val($(n).attr('placeholder'));});$message.html('').append(data.message).slideDown('fast');$message.attr('role','alert');$('.screen-reader-response',$form.closest('.wpcf7')).each(function(){var $response=$(this);$response.html('').attr('role','').append(data.message);if(data.invalidFields){var $invalids=$('<ul></ul>');$.each(data.invalidFields,function(i,n){if(n.idref){var $li=$('<li></li>').append($('<a></a>').attr('href','#'+n.idref).append(n.message));}else{var $li=$('<li></li>').append(n.message);}
$invalids.append($li);});$response.append($invalids);}
$response.attr('role','alert').focus();});};$.ajax({type:'POST',url:wpcf7.apiSettings.getRoute('/contact-forms/'+wpcf7.getId($form)+'/feedback'),data:formData,dataType:'json',processData:false,contentType:false}).done(function(data,status,xhr){ajaxSuccess(data,status,xhr,$form);$('.ajax-loader',$form).removeClass('is-active');}).fail(function(xhr,status,error){var $e=$('<div class="ajax-error"></div>').text(error.message);$form.after($e);});};wpcf7.triggerEvent=function(target,name,detail){var $target=$(target);var event=new CustomEvent('wpcf7'+name,{bubbles:true,detail:detail});$target.get(0).dispatchEvent(event);$target.trigger('wpcf7:'+name,detail);$target.trigger(name+'.wpcf7',detail);};wpcf7.toggleSubmit=function(form,state){var $form=$(form);var $submit=$('input:submit',$form);if(typeof state!=='undefined'){$submit.prop('disabled',!state);return;}
if($form.hasClass('wpcf7-acceptance-as-validation')){return;}
$submit.prop('disabled',false);$('input:checkbox.wpcf7-acceptance',$form).each(function(){var $a=$(this);if($a.hasClass('wpcf7-invert')&&$a.is(':checked')||!$a.hasClass('wpcf7-invert')&&!$a.is(':checked')){$submit.prop('disabled',true);return false;}});};wpcf7.notValidTip=function(target,message){var $target=$(target);$('.wpcf7-not-valid-tip',$target).remove();$('<span role="alert" class="wpcf7-not-valid-tip"></span>').text(message).appendTo($target);if($target.is('.use-floating-validation-tip *')){var fadeOut=function(target){$(target).not(':hidden').animate({opacity:0},'fast',function(){$(this).css({'z-index':-100});});};$target.on('mouseover','.wpcf7-not-valid-tip',function(){fadeOut(this);});$target.on('focus',':input',function(){fadeOut($('.wpcf7-not-valid-tip',$target));});}};wpcf7.refill=function(form,data){var $form=$(form);var refillCaptcha=function($form,items){$.each(items,function(i,n){$form.find(':input[name="'+i+'"]').val('');$form.find('img.wpcf7-captcha-'+i).attr('src',n);var match=/([0-9]+)\.(png|gif|jpeg)$/.exec(n);$form.find('input:hidden[name="_wpcf7_captcha_challenge_'+i+'"]').attr('value',match[1]);});};var refillQuiz=function($form,items){$.each(items,function(i,n){$form.find(':input[name="'+i+'"]').val('');$form.find(':input[name="'+i+'"]').siblings('span.wpcf7-quiz-label').text(n[0]);$form.find('input:hidden[name="_wpcf7_quiz_answer_'+i+'"]').attr('value',n[1]);});};if(typeof data==='undefined'){$.ajax({type:'GET',url:wpcf7.apiSettings.getRoute('/contact-forms/'+wpcf7.getId($form)+'/refill'),dataType:'json'}).done(function(data,status,xhr){if(data.captcha){refillCaptcha($form,data.captcha);}
if(data.quiz){refillQuiz($form,data.quiz);}});}else{if(data.captcha){refillCaptcha($form,data.captcha);}
if(data.quiz){refillQuiz($form,data.quiz);}}};wpcf7.clearResponse=function(form){var $form=$(form);$form.removeClass('invalid spam sent failed');$form.siblings('.screen-reader-response').html('').attr('role','');$('.wpcf7-not-valid-tip',$form).remove();$('[aria-invalid]',$form).attr('aria-invalid','false');$('.wpcf7-form-control',$form).removeClass('wpcf7-not-valid');$('.wpcf7-response-output',$form).hide().empty().removeAttr('role').removeClass('wpcf7-mail-sent-ok wpcf7-mail-sent-ng wpcf7-validation-errors wpcf7-spam-blocked');};wpcf7.apiSettings.getRoute=function(path){var url=wpcf7.apiSettings.root;url=url.replace(wpcf7.apiSettings.namespace,wpcf7.apiSettings.namespace+path);return url;};})(jQuery);(function(){if(typeof window.CustomEvent==="function")return false;function CustomEvent(event,params){params=params||{bubbles:false,cancelable:false,detail:undefined};var evt=document.createEvent('CustomEvent');evt.initCustomEvent(event,params.bubbles,params.cancelable,params.detail);return evt;}
CustomEvent.prototype=window.Event.prototype;window.CustomEvent=CustomEvent;})();;(function($){var windowH=$(window).height();$(window).resize(function(){if((navigator.userAgent.match(/iPhone/i))||(navigator.userAgent.match(/iPod/i))){windowH=window.screen.height;}else{windowH=$(window).height();}
checkSize();})
$(document).ready(function(){externalLinks();checkSize();goUp();if($('.home').length>0){goDown();headerHeight();$(window).resize(function(){headerHeight();})}
if($('.single-thematique, .page-template-template-referentiel').length>0){stickyNavArticlesInit();articleMB();$(window).resize(function(){articleMB();})}
if($('.pyramids').length>0){pyramid();}
if($('.single-thematique').length>0){relationSectionPos();relationSectionScroll();ressources_toggle();$(window).resize(function(){relationSectionPos();relationSectionScroll();})
$(document).scroll(function(){relationSectionScroll();})
relationActions();}})
$(window).load(function(){if($('.home').length>0){homeElements();$(window).resize(function(){homeElements();})}})
function headerHeight(){$('.page-header-content').css('height',windowH-$('#masthead').height());}
function checkSize(){if($(window).width()>925){$('html').removeClass('small-screen');}else{$('html').addClass('small-screen');}}
function externalLinks(){$('a:external').attr('target','_blank').addClass('external');}
$.expr[':'].external=function(obj){return!obj.href.match(/^mailto\:/)&&(obj.hostname!=location.hostname)&&!obj.href.match(/^javascript\:/)&&!obj.href.match(/^$/)};function homeElements(){var halfH=0;$('#actions article').each(function(i){halfH=$(this).height()>halfH?$(this).height():halfH;if(i%2!=0){$('#actions article').eq(i).css('height',halfH);$('#actions article').eq(i-1).css('height',halfH);halfH=0;}})}
function goDown(){$('.page-header .godown').on('click',function(event){event.preventDefault();$('html, body').stop().animate({scrollTop:$('.page-header').height()+$('.page-header').offset().top},300);})}
var currentArticle;var scrolling=false;function stickyNavArticlesInit(articleContainer){var selector=typeof articleContainer==='undefined'?$('section.content'):articleContainer;var relation=selector.attr('class')=='content'?false:true;var nav;var navW;var navOW;var navT;var beforeH;if(!relation)
currentArticle=$('.nav-sub-article-title',nav).first().data('article-id');stickyNavArticlesVars();stickyNavArticles();$(window).resize(function(){stickyNavArticlesVars();})
if(!relation){$(window).scroll(function(){stickyNavArticles();})}else{$(selector).scroll(function(){stickyNavArticles();})}
stickyNavArticlesLink();articleAutoScroll();sommaire();function stickyNavArticlesLink(){$('.nav-article-title, .nav-sub-article-title',nav).on('click',function(event){event.preventDefault();$(this).closest('.nav-sticky').removeClass('open');if($(this).closest('.nav-article-title').length>0){event.stopPropagation();}
var articleId=$(this).data('article-id');scrolling=true;var scrollPos=!relation?$('.'+articleId,selector).offset().top-beforeH:$('.'+articleId,selector).position().top+$(selector).scrollTop()-beforeH;if(!relation&&scrollPos!=$(document).scrollTop()){var current=$(this).hasClass('nav-article-title')?$('.nav-sub-article-title',this).first():$(this);currentArticle=current.data('article-id');changeRelation('down');}
var scrolled=!relation?$('html, body'):$(this).closest('.relation-nav').next('.relation-content');scrolled.stop().animate({scrollTop:scrollPos+1},300,function(){scrolling=false;});})}
function stickyNavArticlesVars(){beforeH=$('html').hasClass('small-screen')?0:parseInt($('.content').css('padding-top'),10);nav=!relation?$('.nav-sticky',selector):$('.nav-sticky',selector.prev());navArticle=!relation?$('.nav-articles',selector):$('.nav-articles',selector.prev());navW=nav.width();navOW=nav.outerWidth(true);navT=navArticle.offset().top;}
function stickyNavArticles(){var windowS=$(window).scrollTop();if(!relation){$('.thematique-content, .content .referentiel-content').css('padding-left',navOW);if(windowS>=navT-beforeH){nav.css({position:'fixed',top:5,width:navW})}else{nav.css({position:'absolute',top:beforeH})}}
$('.article-part',selector).each(function(i){var part=$(this);var partH=part.height();var partT=part.offset().top;var partS=partT-windowS-beforeH;var percentage=0;if(-partS>partH){percentage=100;}else if(partS<0){percentage=(-partS/partH)*100;}
if(percentage!=0&&percentage!=100){$('.nav-article-title .nav-sub-article',nav).eq(i).slideDown(200);$('.nav-article-title .nav-article-title-inner',nav).eq(i).addClass('active');}else{$('.nav-article-title .nav-sub-article',nav).eq(i).slideUp(200);$('.nav-article-title .nav-article-title-inner',nav).eq(i).removeClass('active');}
$('.nav-article-title-inner .read',nav).eq(i).css('width',percentage+'%');})
var current=false;$('.sub-article-part',selector).each(function(i){var part=$(this);var partH=part.height();var partT=part.offset().top;var partS=partT-windowS-beforeH;var percentage=0;if(-partS>partH){percentage=100;$('.nav-article-title .nav-sub-article-title',nav).eq(i).removeClass('next');}else if(partS<0){percentage=(-partS/partH)*100;$('.nav-article-title .nav-sub-article-title',nav).eq(i).removeClass('next');}else{$('.nav-article-title .nav-sub-article-title',nav).eq(i).addClass('next');}
if(percentage!=0&&percentage!=100){$('.nav-sub-article-title .nav-sub-article-title-inner',nav).eq(i).addClass('active');}else{$('.nav-sub-article-title .nav-sub-article-title-inner',nav).eq(i).removeClass('active');}
if(!relation){if(percentage>0&&percentage<100&&!scrolling){currentArticle=$('.nav-article-title .nav-sub-article-title',nav).eq(i).data('article-id');current=true;}}
$('.nav-sub-article-title-inner .read',nav).eq(i).css('width',percentage+'%');})
if(!current&&!relation){currentArticle=$('.nav-article-title .nav-sub-article-title.next',nav).first().data('article-id');}}
function articleAutoScroll(){var articles=[];var flag=false;selectRelation();$(document).scroll(function(){selectRelation();})
function selectRelation(){var documentS=$(document).scrollTop();var beforeH=parseInt($('.content').css('padding-top'),10);$('.sub-article-part',selector).each(function(){var id=$(this).data('id');var articleT=$(this).offset().top;var articleH=$(this).outerHeight(true);if(articleT+articleH<documentS+windowH){if(articles[id]=='bottom'&&!flag){flag=true;var next=$(this).next().length>0?$(this).next():$(this).parent().next();if(next.length>0){var nextSub=next.hasClass('article-part')?$('.sub-article-part',next).first():next;if(!scrolling){if(!relation){currentArticle=nextSub.data('id');changeRelation('down');}
flag=false;}else{flag=false;}}else{flag=false;}}
articles[id]='top';}else{if(articles[id]=='top'&&!scrolling&&!relation){changeRelation('up');}
articles[id]='bottom';}})}}
function changeRelation(dir){if($('.relation.active').length>0){if(dir=='down')
$('.relation.active').stop().animate({top:-100+'%'},300,function(){$(this).removeClass('active')});else if(dir=='up')
$('.relation.active').stop().animate({top:100+'%'},300,function(){$(this).removeClass('active')});else
$('.relation.active').stop().animate({left:60},300,function(){$(this).removeClass('active')});}
var articleNow=currentArticle;if($('.relation-'+articleNow).length>0){if(!$('.relation-'+articleNow).hasClass('loaded')&&!$('.relation-'+articleNow).hasClass('loading')&&$('#main').hasClass('relation-active')){var container=$('.relation-'+articleNow);var pyramids=container.data('pyramid');var theories=container.data('referentiel');loadRelation(container,pyramids,theories);}
if(dir=='down')
$('.relation-'+articleNow).css('top','100%');else if(dir=='up')
$('.relation-'+articleNow).css('top','-100%');else
$('.relation-'+articleNow).css('left','60');$('.relation-'+articleNow).addClass('active').stop().animate({top:0,left:0},300);}}
function sommaire(){$('.nav-title',nav).on('click',function(){$(this).parent().toggleClass('open');})}}
function pyramid(articleContainer){var selector=typeof articleContainer==='undefined'?$('body'):articleContainer;var title=typeof articleContainer==='undefined'?'':'.visible';$('.pyramid-title'+title,selector).on('click',function(){var index=$(this).index();$(this).closest('.pyramids').find('.pyramid-content .active').removeClass('active').slideUp(200);$(this).closest('.pyramids').find('.pyramid-titles .active').removeClass('active');$(this).toggleClass('active').siblings().removeClass('active').parent().next().children('div').stop().eq(index).slideToggle(200).toggleClass('active').siblings().slideUp(200).removeClass('active');})
$('.pyramid-content .close',selector).on('click',function(){$(this).parent().stop().slideUp(200).removeClass('active').parent().prev().children().removeClass('active');})
$('.pyramid-category').on('click',function(){$(this).next('.pyramid-category-description').stop().slideToggle(200).siblings('.pyramid-category-description').stop().slideUp(200);})
pyramidToggle();function pyramidToggle(){$('.pyramids ~ .toggle .toggle-title').on('click',function(){$(this).toggleClass('active').next('.toggle-content').stop().slideToggle(300);})
$('.pyramids').each(function(){var toggleH=0;$(this).nextAll('.toggle').each(function(){var thisH=$(this).outerHeight(true);if(thisH>toggleH)
toggleH=thisH;})
$(this).nextAll('.toggle').css('min-height',toggleH);})}}
function articleMB(){$('.sub-article-part').css('margin-bottom',windowH/2);}
function relationSectionPos(){var content=$('section.content');var top=content.position().top;var maxH=content.outerHeight();$('section.relations').css({display:'block',height:windowH,top:top,maxHeight:maxH})
var relationH=$('section.relations').height();$('.nav-relation-title').width(relationH);}
function relationSectionScroll(){var documentS=$(document).scrollTop();var top=$('section.content').position().top;if(documentS>top){$('section.relations').css({position:'fixed',top:0})
var footerT=$('#colophon').offset().top;if(documentS>=footerT-windowH){$('section.relations').css({height:footerT-documentS})}else{$('section.relations').css({height:windowH})}
var relationH=$('section.relations').height();$('.nav-relation-title').width(relationH);}else{$('section.relations').css({position:'absolute',top:top})}}
function relationActions(){$('.nav-relation-title, .relation-nav .close').on('click',function(){$('#main').toggleClass('relation-active');if($('#main').hasClass('relation-active')){var container=$(this).parent();if(!container.hasClass('loaded')){var pyramids=container.data('pyramid');var theories=container.data('referentiel');loadRelation(container,pyramids,theories);var articleNow=currentArticle;$('.single-thematique .relation-active .thematique .thematique-content').on('webkitTransitionEnd otransitionend oTransitionEnd msTransitionEnd transitionend',function(event){if((event.originalEvent.propertyName=='padding-left'||event.originalEvent.propertyName=='padding')&&$('#main').hasClass('relation-active')){scrolling=true;$('html, body').stop().animate({scrollTop:$('.thematique .'+articleNow).offset().top-80},300,function(){scrolling=false;})}})}}})}
var loaded=[];function loadRelation(container,pyramids,theories){var articleContainer=$('.relation-content',container);var loadedId=container.data('id');if(!articleContainer.hasClass('loading')&&$.inArray(loadedId,loaded)==-1){articleContainer.addClass('loading');loaded.push(container.data('id'));var data={action:'load_relation',pyramids:pyramids,theories:theories}
$.post(ajaxurl,data,function(response){var articleParts=JSON.parse(response);articleContainer.append(articleParts.content).addClass('loaded').removeClass('loading');articleContainer.prev().append(articleParts.nav);pyramid(articleContainer);stickyNavArticlesInit(articleContainer);})}}
function goUp(){$(document).scroll(function(){if($(document).scrollTop()>windowH){$('.go-up').fadeIn(200);}else{$('.go-up').fadeOut(200);}})
$('.go-up').on('click',function(){$('html, body').stop().animate({scrollTop:0},300);})}
function ressources_toggle(){$('.ressources').on('click',function(){if($(this).hasClass('active')){$(this).removeClass('active');}else{$(this).addClass('active');}
$('div',$(this)).toggle('slow');});}}(jQuery));(function(){var isWebkit=navigator.userAgent.toLowerCase().indexOf('webkit')>-1,isOpera=navigator.userAgent.toLowerCase().indexOf('opera')>-1,isIE=navigator.userAgent.toLowerCase().indexOf('msie')>-1;if((isWebkit||isOpera||isIE)&&document.getElementById&&window.addEventListener){window.addEventListener('hashchange',function(){var id=location.hash.substring(1),element;if(!(/^[A-z0-9_-]+$/.test(id))){return;}
element=document.getElementById(id);if(element){if(!(/^(?:a|select|input|button|textarea)$/i.test(element.tagName))){element.tabIndex=-1;}
element.focus();window.scrollBy(0,-53);}},false);}})();